#pragma once
#include "utils.h"
#include "RegistryUtils.h"
#include <string>
#include <shlwapi.h>
DWORD GetStartupPrograms();
DWORD GetServices();
DWORD GetFilesRelateOpenCommands();
DWORD GetUserInit();
DWORD GetImageHijack();
DWORD GetScreenSave();
DWORD GetWaitforBackdoor();
DWORD GetComHijack();
DWORD GetAppInit_Dlls();
DWORD GetMSDTCBackdoor();
DWORD GetUserInitMprLogonScript();
DWORD GetShadowAccount();
DWORD GetRundll32Backdoor();
DWORD GetProcesses();
DWORD GetTCPConnection();